name: izihirwe_pro_v2
description: IZIHIRWE Employee Management
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  cloud_firestore: ^4.15.0
  provider: ^6.1.1
flutter:
  uses-material-design: true
